@startuml Vrai/Faux

class Professeur

class Discipline

class Cours

class Etudiant

<> diamond
Professeur "1" -- diamond
diamond -- "*" Discipline
diamond - Cours
Etudiant "5..30" -- "*" Cours

@enduml